FROM node:11.12.0-stretch-slim

# Create app directory
WORKDIR /usr/ScienceDbStarterPack/graphql-server

# Copy generated code into the skeleton GraphQL-Server
COPY . .

# Clone the skeleton project and install dependencies
RUN chmod u+x ./migrateDbAndStartServer.sh && \
  rm .git* && \
  mv ./config/config_postgres_docker.json ./config/config.json && \
  apt-get update && apt-get install -y autoconf libtool && \	
  npm install 
  

EXPOSE 3000
